apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: nginx-http
    nodePort: 31380
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
