apiVersion: autoscaling.containers.ai/v1alpha1
kind: AlamedaScaler
metadata:
  name: nginx-scaler
  namespace: mynginxproj
spec:
  enableExecution: false
  nginx:
    targetResponseTime: 200
    exporterNamespace: openshift-ingress
    maxReplicas: 40
    minReplicas: 1
    replicaMarginPercentage: 40
    selector:
      matchLabels:
        app: nginx
    service: nginx-service
  policy: stable
  scalingTool:
    type: hpa
  type: nginx
